HookIntoNCP: true
Permissions:
  speeds:
    - 2
    - 5
    - 10
    - 15
    - 20
    - 30
    - 50
NoClipProtection:
  - CONTACT
  - DROWNING
  - FALLING_BLOCK
  - FIRE
  - FIRE_TICK
  - LAVA
  - SUFFOCATION
  - VOID