name: DaFlightManagerBukkit
main: me.dags.daflightmanager.DaFlightManagerBukkit
version: ${project.version}
author: dags_
softdepend: [NoCheatPlus]
website: ${project.url}

commands:
  dfrefresh:
    description: Refresh DaFlight perms command
    usage: /dfrefresh
    aliases: [dfr]
    permission: DaFlight.refresh
    permission-message: Ain't got perms fo dat!
  dfreload:
      description: Reload the config
      usage: /dfreload
      permission: DaFlight.reload
      permission-message: Ain't got perms fo dat!

permissions:
  DaFlight.refresh.self:
    description: Allow user to refresh their daflight permissions
    default: op
  DaFlight.refresh.other:
    description: Allow user to refresh another user's daflight permissions
    default: op
  DaFlight.refresh.all:
    description: Allow user to refresh all user's daflight permissions
    default: op
  DaFlight.fullbright:
    description: Allow user to use DaFlight's fullbright
    default: op
  DaFlight.flymod:
    description: Allow user to use DaFlight's flymod
    default: op
  DaFlight.softfall:
    description: User doesn't take fall damage whilst flying
    default: op
  DaFlight.noclip:
    description: Allow use to fly through solid blocks
    default: op
  DaFlight.speed:
    description: Base speed permission
    default: op