name: DaFlightManager
main: me.dags.DaFlightManager.DaFlightManager
version: 0.0.2
author: dags_
softdepend: [NoCheatPlus]

permissions:
  DaFlight.user:
    default: op
    children:
      DaFlight.fullbright: true
      DaFlight.flymod: true
      DaFlight.speed.2: true
  DaFlight.mod:
    default: op
    children:
      DaFlight.fullbright: true
      DaFlight.flymod: true
      DaFlight.speed.7: true
  DaFlight.admin:
    default: op
    children:
      DaFlight.fullbright: true
      DaFlight.flymod: true
      DaFlight.speed.15: true
  DaFlight.*:
    default: op
    children:
      DaFlight.fullbright: true
      DaFlight.flymod: true
      DaFlight.speed.50: true
  DaFlight.fullbright:
    description: Allow user to use DaFlight's fullbright
    default: op
  DaFlight.flymod:
    description: Allow user to use DaFlight's flymod
    default: op
  DaFlight.speed.2:
    description:
    default: op
  DaFlight.speed.5:
    description:
    default: op
  DaFlight.speed.7:
    description:
    default: op
  DaFlight.speed.10:
    description:
    default: op
  DaFlight.speed.15:
    description:
    default: op
  DaFlight.speed.25:
    description:
    default: op
  DaFlight.speed.50:
    description:
    default: op