name: DaFlightManager
main: me.dags.daflightmanager.DaFlightManager
version: ${project.version}-r${buildNumber}
author: dags_
softdepend: [NoCheatPlus]
website: ${project.url}

permissions:
  DaFlight.fullbright:
    description: Allow user to use DaFlight's fullbright
    default: op
  DaFlight.flymod:
    description: Allow user to use DaFlight's flymod
    default: op
  DaFlight.softfall:
    description: User doesn't take fall damage whilst flying
    default: op
  DaFlight.noclip:
    description: Allow use to fly through solid blocks
    default: op
  DaFlight.speed:
    description: Base speed permission
    default: op